name: experiment_sdk_flutter
description: Experiment SDK for Flutter powered by ProductMinds. Amplitude Experiment is a tool to manage and orchestrate AB testing and feature flagging. 
version: 1.3.1
homepage: https://github.com/productminds/experiment_sdk_flutter

environment:
  sdk: ">=2.19.1 <3.0.0"
  flutter: 3.7.12

dependencies:
  amplitude_flutter: ^3.15.0
  flutter:
    sdk: flutter
  http: ^1.0.0
  shared_preferences: 2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.3

flutter:
